import Head from "next/head";
import { server } from "@/config/index";
import Card from "@/components/Card";
import { PostProps } from "@/components/Card";
import style from "@/styles/Home.module.sass";

export async function getServerSideProps() {
  const data = await fetch(`${server}/api/get-posts`);
  const posts = await data.json();
  return { props: { posts } };
}

export default function Home({ posts }: any) {
  return (
    <>
      <Head>
        <title>View Posts</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={style.main}>
        {posts.map((post: PostProps) => (
          <Card key={post.id} {...post} />
        ))}
      </main>
    </>
  );
}
