import Head from "next/head";
import { server } from "@/config";
import Card from "@/components/Card";
import { PostProps } from "@/components/Card";
import style from "@/styles/Home.module.sass";
import {MouseEvent} from "react";
import {useState} from "react";

export async function getServerSideProps() {
  const data = await fetch(`${server}/api/get-posts`);
  const posts = await data.json();
  return { props: { posts } };
}

export default function Home({ posts }: any) {

    const [postData, setPostData] = useState<PostProps[]>(posts)

    const handleFav = async (e:MouseEvent<HTMLButtonElement>, id: string) => {
        e.preventDefault()
        try{
            const res = await fetch(`${server}/api/toggle-favorite?id=${id}`,{
                method: 'PUT',

            })
            const data = await res.json()
            const newPostData = postData.map((post: PostProps) => {
                if(post.id === id){
                    return {...data}
                }
                return post
            })
            setPostData(newPostData)
        }catch (e) {
            console.log(e)
        }
    }

  return (
    <>
      <Head>
        <title>Posts</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={style.main}>
        {postData.map((post: PostProps) => (
          <Card onFav={(e:MouseEvent<HTMLButtonElement>) => handleFav(e, post.id)} key={post.id} {...post} />
        ))}
      </main>
    </>
  );
}
